# Generated by Django 4.1.7 on 2023-03-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('html_tag', models.CharField(max_length=25)),
                ('class_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
