# Generated by Django 4.1.7 on 2023-04-23 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_management', '0006_rename_name_newsportal_portal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('catagory', models.CharField(choices=[('SP', 'SPORTS'), ('ENT', 'ENTERTAINMENT'), ('POL', 'POLITICS')], max_length=50)),
                ('rank', models.IntegerField()),
                ('text', models.TextField()),
            ],
        ),
    ]
